### ISSUE TITLE
KeyNotFoundException

### ISSUE THREAD

**Issue by SFieuws** [AlenToma/FastDeepCloner#2] opened 2018-12-05 09:01 UTC
When trying to clone my class, I get the 'System.Collections.Generic.KeyNotFoundException'

This is my clone method:
```
public Enterprise Clone() {
    return FastDeepCloner.DeepCloner.Clone(this);
}
```

Anyone can help?

**Comment by AlenToma** [comment] 2018-12-05 13:40
could you show me the `Enterprise` Class, so i could test it.

**Comment by SFieuws** [comment] 2018-12-05 13:43
here is a gist with my class:
https://gist.github.com/SFieuws/c12abaa3a7f9c598af77645e719e94cb

**Comment by AlenToma** [comment] 2018-12-05 14:13
ok as if right now the library cant handle Interface eg ICollection, but it will be fixed in the new version.
so Promoties  and OpeningHours  are not cloned. 
and i still not getting the error. the cause of the error must exist in the other classes eg `Promotion `or `OpeningHour` or `Address` or `User`. could you also post those. 
the new version will be published after we examin the error you got

**Comment by SFieuws** [comment] 2018-12-05 14:48
This is unfortunate. As I really need a deep copy of everything in my class.
This gist consist of the other classes.
https://gist.github.com/SFieuws/5988d08f3fc930ee3a6bbd119e96d09f

**Comment by AlenToma** [comment] 2018-12-05 15:09
ok, Im still not getting the error, what platform are you using? is it NETSTANDARD1_3

**Comment by SFieuws** [comment] 2018-12-05 15:29
It is an UWP app

**Comment by AlenToma** [comment] 2018-12-05 15:35
Ok i think that this error are caused by NETSTANDARD1_3. i have published new package 
FastDeepCloner 1.1.2, it will be available after few minutes. and fixed a code that may throw KeyNotFoundException in a Dictionary. try it and tell me if the error still exist.
and also fixed the inteface (ICollection) clone issue

**Comment by SFieuws** [comment] 2018-12-05 15:49
It looks like it works. Thank you for the extreme fast support!

**Comment by AlenToma** [comment] 2018-12-05 15:52
Good and i made a smal changes so it can now create ObservableCollection instead of List. make sure to update to FastDeepCloner 1.1.3 after few minutes.
will now close this issue and good luck.

**Closed as completed by AlenToma** 2018-12-05 15:52 UTC
