### ISSUE TITLE
Probable thread safety issue

### ISSUE THREAD

**Issue by DavidR91** [AlenToma/FastDeepCloner#13] opened 2020-06-02 15:42 UTC
I keep seeing this exception:

```
'An item with the same key has already been added. Key: <TYPE OF THE CLASS I'M CLONING>'

at FastDeepCloner.FastDeepClonerCachedItems.Creator(Type type, Boolean validateArgs, Object[] parameters)
at FastDeepCloner.FastDeepClonerSettings.<>c.<.ctor>b__12_0(Type type)
at FastDeepCloner.ReferenceClone.ReferenceTypeClone(Dictionary`2 properties, Type primaryType, Object objectToBeCloned, Object appendToValue)
at FastDeepCloner.ReferenceClone.Clone(Object objectToBeCloned)
at FastDeepCloner.DeepCloner.Clone(Object objectToBeCloned, FieldType fieldType)
at NetSupport.DeepClone[T](T original) in 
```

of note is that this only consistently happens when two threads are calling 

`FastDeepCloner.DeepCloner.Clone(value, FastDeepCloner.FieldType.Both);`

at the same time. It does not occur every time

Based on the locks inside FastDeepClonerCachedItems I'm assuming the cloner is supposed to be thread safe and this is just a bug?

Or should I should not be using this from multiple threads in parallel?

**EDIT**: I've been seeing this on 1.3.3, I've just updated to 1.3.5 and going to check if it still occurs

**Comment by DavidR91** [comment] 2020-06-03 10:34
Can confirm this is still happening with 1.3.5.

Only additional info I can give is that all of the instances I get so far are nested classes - e.g. 

`An item with the same key has already been added. Key: NetActions+Group`

where `Group` is a class nested inside of NetActions

**Comment by IgorZudov** [comment] 2020-06-07 09:20
I have the same issue with 1.3.5 version.

**Comment by andyast** [comment] 2020-10-02 15:31
I can confirm when using this in a AspNetCore Web Application we are getting threading issues.   Tracked it back to here:  https://github.com/AlenToma/FastDeepCloner/blob/2d3de92b0154b9fd28c067ba60a1fc5ca0d5f40d/source/FastDeepCloner/FastDeepClonerCachedItems.cs#L754

`System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at FastDeepCloner.FastDeepClonerCachedItems.GetFastDeepClonerProperties(Type primaryType)
   at FastDeepCloner.ReferenceClone.Clone(Object objectToBeCloned)
   at FastDeepCloner.DeepCloner.Clone[T](T objectToBeCloned, FieldType fieldType)`

**Comment by coderdnewbie** [comment] 2021-03-10 15:34
SemaphoreSlim looks like a good way to solve this. An example of what I mean is here:

https://gist.github.com/ntrpnr/a8cd8b31ef24fbd6f9a3277c5bf471f6

**Comment by AlenToma** [comment] 2021-03-10 21:54
I have started with a new project and I really do not have a time to fix this.

But here is a quick solution you could have 

Create a Clone extension

```csharp
private static object locker = new object();
public static T Clone<T>(this T item, FastDeepCloner.FieldType fieldType = FastDeepCloner.FieldType.PropertyInfo){

   lock(locker){
    return FastDeepCloner.DeepCloner.Clone(item, fieldType);     
   }
}


```
And then simple call `new Example().Clone();`

this way you could handle the multithreading issue.

**Comment by thomhurst** [comment] 2021-08-03 11:49
I've created PullRequest #16  which I think should help fix this.

**Comment by AlenToma** [comment] 2021-08-03 16:30
Have checket the pull request, and seems good. did you test this code on all deferent platforms?

**Comment by thomhurst** [comment] 2021-10-08 13:54
Yep, it was fine from my testing! Feel free to do your own.
Would like to get this merged to fix the odd exception I get when using this library.

**Comment by AlenToma** [comment] 2021-10-16 13:53
I have merged and published a new package for this issue. thx for the help.

**Closed as completed by AlenToma** 2021-10-16 13:53 UTC
Labels: bug
